# -*- coding: utf-8 -*-
"""Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XssjBRaU9OEbG4NK0JVAatbHVNeWasAa
"""

import streamlit as st
import pandas as pd
import pickle

# Загрузка PMML модели
with open('decision_tree_model.pkl', 'rb') as file:
    loaded_model = pickle.load(file)

# Создание интерфейса Streamlit
st.title('Предсказание дохода')

# Вводные данные (только необходимые поля)
age = st.number_input('Возраст', min_value=0, max_value=100)
relationship = st.selectbox('Семейное положение', ['Not-in-family', 'Husband', 'Wife', 'Own-child', 'Unmarried', 'Other-relative'])
capital_gain = st.number_input('Прирост капитала', min_value=0)
education_num = st.number_input('Количество лет обучения', min_value=0)
marital_status = st.selectbox('Семейное положение', ['Never-married', 'Married-civ-spouse', 'Divorced', 'Married-spouse-absent', 'Separated', 'Married-AF-spouse', 'Widowed'])

# Кнопка для запуска предсказания
if st.button('Предсказать'):
    # Создание DataFrame из введенных данных (только необходимые столбцы)
    input_data = pd.DataFrame({
        "age": [age],
        "relationship": [relationship],
        "capital_gain": [capital_gain],
        "education_num": [education_num],
        "marital_status": [marital_status]
    })

    # Предсказание
    prediction = loaded_model.predict(input_data)
    
    if prediction.loc[0][0] == 1:
      st.write("Предсказанный доход: >50K")
    else:
      st.write("Предсказанный доход: <=50K")
